### ISSUE TITLE
review-jsbook のオプションで paper=a4 とすると左右どちらかの余白サイズが異なってしまう

### ISSUE THREAD

**Issue by bynnchapu** [kmuto/review#1236]
Re:VIEW のバージョンは 3.0 を使っています。

設定ファイル `config.yml` で `review-init` コマンドで生成されるデフォルトの `texdocumentclass` では左右の余白サイズが同じ形で出力されます。

```
texstyle: ["reviewmacro"]
texdocumentclass: ["review-jsbook", "media=print,paper=a5"]
```

![a5](https://user-images.githubusercontent.com/1008151/50373932-2d015a80-0629-11e9-95c2-fbd7c1070e1b.png)

このとき `texdocumentclass` のオプションを `paper=a4` とすると、本文内の左右どちらかの余白サイズが増えてしまいます。

```
texstyle: ["reviewmacro"]
texdocumentclass: ["review-jsbook", "media=print,paper=a4"]
```

![a4](https://user-images.githubusercontent.com/1008151/50373983-26271780-062a-11e9-95b7-db8b005ef851.png)

なお、プリンターで直接トンボなしで出力したいので、本番時には以下のようにしたいと思っています。

```
texstyle: ["reviewmacro"]
texdocumentclass: ["review-jsbook", "media=print,paper=a4,tombopaper=a4"]
```

トンボの出力はこれで抑止されるのですが、このときも余白サイズが増えてバランスがずれてしまいます。
`paper=a4` としたときも `paper=a5` と同様に左右の余白サイズが同じように揃えたいのですが、どうしたらよいでしょうか。

**Comment by munepi** [comment]
まず、大前提として、これらの挙動は、（`jsbook.cls` 既定の用紙サイズのみを切り替えているだけで、） `jsbook.cls` そのものの仕様です。
実際に、既定の用紙サイズを A4 のみならず、B5 に変えていただいても、（jsbook.clsの版面設計の自動計算により、）似たような出力になります。

実現なさりたいことは、A5のような余白（ノド、小口）が左右で等しくなるような版面ですよね？
つまり、版面が左右中央に配置される。

review-jsbook.cls において、 A4 用紙サイズ、本文文字サイズ 10pt（デフォルト）、40文字にする場合は、 `line_length=40zw` を texdocumentclass にわたしてあげれば、期待した出力になりませんでしゅか？



``` yaml
## A: default: media=print, paper=a4
texdocumentclass: ["review-jsbook", ""]

## B: line_length=40zw 
texdocumentclass: ["review-jsbook", "line_length=40zw"]

## 上記、AとBをぜひ比較なさってください！　もちろん、下記は B と同じ設定ですね。
# texdocumentclass: ["review-jsbook", "media=print, paper=a4,line_length=40zw"]
```

![2018-12-22 22 47 30](https://user-images.githubusercontent.com/583148/50375107-a144f980-063b-11e9-8f5a-a085eb0566ae.png)

![2018-12-22 22 46 47](https://user-images.githubusercontent.com/583148/50375095-7f4b7700-063b-11e9-95b3-830e06313603.png)
