### ISSUE TITLE
本編を部構成にすると目次で「後付け」が現れる位置が異様

### ISSUE THREAD

**Issue by goto-yuki** [kmuto/review#1262]
# 目次に「後付け」が現れる位置について

Re:VIEW3.0.0のHTMLビルダにおいて、本編を部構成にすると目次の中で「後付け」が現れる位置が異様です。

## 部構成で付録なしの場合

```
PREDEF:
  - preface.re

CHAPS:
 - part_01.re:
   - chapter_01.re

 - part_02.re:
   - chapter_02.re

APPENDIX:

POSTDEF:
   - postface.re
```

「後付け」が本編の最後の部の直後に入ってしまいます。

![toc-0](https://user-images.githubusercontent.com/46343265/51718715-eb315d00-2089-11e9-8eb2-d85250ce3515.jpg)

## 部構成で付録ありの場合
```
PREDEF:
  - preface.re

CHAPS:
 - part_01.re:
   - chapter_01.re

 - part_02.re:
   - chapter_02.re

APPENDIX:
   - appendix.re

POSTDEF:
   - postface.re
```

「後付け」が付録の中に入ってしまいます。
![toc-1](https://user-images.githubusercontent.com/46343265/51718728-fedcc380-2089-11e9-9a79-5348d9ab0440.jpg)

## 部構成にしない場合
```
PREDEF:
  - preface.re

CHAPS:
   - chapter_01.re
   - chapter_02.re

APPENDIX:
   - appendix.re

POSTDEF:
   - postface.re
```
「後付け」は正しい位置に入ります。

![toc-2](https://user-images.githubusercontent.com/46343265/51718808-41060500-208a-11e9-9808-265471ee3831.jpg)
