### ISSUE TITLE
2.5版で pdf でのクオートが全角になる問題

### ISSUE THREAD

**Issue by t-cool** [kmuto/review#1419]
Re:VIEW 2.5版を利用させていただいて、次のように Dockerでビルドを行い、pdf を生成しています。

```
version: 2

jobs:
  build:
    docker:
      - image: nuitsjp/mdview:2.5
    steps:
      - checkout
      - run:
          name: Build PDF
          command: |
            review-pdfmaker config.yml
          working_directory: ./
      - store_artifacts:
          path: ./book.pdf
          destination: book.pdf```
```

ビルドを行うと、原稿の *.re では半角のクオート ' が、pdf では全角のクオート’ に変換されてしまします。

pdf でも原稿の通りに半角で出力するにはどのようにすればいいでしょうか？

ご助言いただけると助かります。
よろしくお願いします。
