### ISSUE TITLE
コードハイライトのデフォルト言語を設定したい

### ISSUE THREAD

**Issue by kdmsnr** [kmuto/review#403]
config.yml の highlight に追加する感じですかねえ。

```
highlight:
   lang: ruby
   html: pygments
   latex: listings
```
