### ISSUE TITLE
表紙の「発行」、奥付の「発行所」が変更できるように

### ISSUE THREAD

**Issue by demuyan** [kmuto/review#438]
同人誌印刷を行う場合、印刷所のガイドラインにより表紙の「ABC印刷所（株）　発行」や奥付の「発行所：ABC印刷（株）」の表記がNGなことがあります。

そこを「ABC印刷（株）　発行」や「印刷所：ABC印刷（株）」といったように差し替えできるようにならないでしょうか。

**Comment by takahashim** [comment]
この件、対応方法がわかりにくくてすみません…。

印刷所と発行所の問題は、 #328 で問題としてあげられ、その際の修正対応により、将来的に `pbl` が「発行所」、 `prt` が「印刷所」に変更されることになりました。

現状では、上記のように修正した上で、locale.ymlには

```yml
locale: 'ja'
pbl: "発行所"
prt: "印刷所"
```

と書き、またconfig.ymlには

```yml
aut: ["高橋征義"]
pbl: XYZ出版
prt: ABC印刷（株）
```

などと書くと、以下のように記載されるようになります。

![prt-pbl2](https://cloud.githubusercontent.com/assets/10401/8506919/fcbb08fc-2266-11e5-933e-5805b6f4a2b1.png)
