### ISSUE TITLE
PDF作成時にLuaTeX用のTeX文書が作成されない

### ISSUE THREAD

**Issue by huideyeren** [kmuto/review#451]
LuaTeX-jaを変換エンジンにして文書を作成しようと考えておりますが、
変換の際にｐLaTeX用のTeX文書が作成されてしまいます。

なお、TeX用の設定は以下のとおりです。

``` yaml
# LaTeX用のスタイルファイル(styディレクトリ以下に置くこと)
texstyle: reviewmacro
# LaTeX用のdocumentclassを指定する
# ここの設定が結構難しい
texdocumentclass: ["ltjsbook", "b5j,openany,oneside,papersize=b5j,notitlepage"]
# LaTeX用のコマンドを指定する(platex or lualatex)
texcommand: "lualatex"
# LaTeX用のオプションを指定する(default: "-kanji=#{kanji}")
# texoptions: "-kanji=utf-8"
# LaTeX用のdvi変換コマンドを指定する(dvipdfmx)
dvicommand: ""
# LaTeX用のdvi変換コマンドのオプションを指定する
dvioptions: ""
```

加えて、スタイルファイルは以下のとおりです。

``` tex
%% from review-pdfmaker
\usepackage{luatexja-fontspec}
\newopentypefeature{PKana}{On}{pkna}
\setmainjfont[
    JFM=prop,PKana=On,Kerning=On,
    BoldFont={IPAexGothic},
    ItalicFont={IPAexMincho},
    BoldItalicFont={IPAexGothic}
]{IPAexMincho}
\setsansjfont{IPAexGothic}
\ltjsetparameter{jacharrange={-2,-3}}
\usepackage{fancyhdr}
\pagestyle{fancy}
% \input{jdummy.def}

%% ペーパーサイズの設定
% \special{papersize=182truemm,257truemm}
% \usepackage[top=18truemm,bottom=19truemm,left=16truemm,right=16truemm]{geometry}

%% 章番号を消す

%% 多言語用設定
% \usepackage{CJK}
% \usepackage[utf8]{inputenc}
% \usepackage[T1,T2A]{fontenc}

%% ハイパーリンクの色を無効に
% \hypersetup{colorlinks=false}
% \usepackage{layout}

%% コードブロックに枠線をつける
% \let\OrigVerbatim\OriginalVerbatim
% \renewcommand{\OriginalVerbatim}[1][1]{\OrigVerbatim[#1,frame=single]}

%% 和文多書体の設定
% \usepackage{palatino}
% \usepackage[deluxe,expert]{otf}
% \renewcommand{\headfont}{\gtfamily\sffamily\bfseries}
% \renewcommand{\emph}[1]{\textmg{\textsf{#1}}}

% \makeatletter
% \def\plainifnotempty{%
% \thispagestyle{plainfoot}% 元は plainhead
% }
% \makeatother
% %% normal ページスタイルの再定義
% \fancypagestyle{normal}{
% \fancyhf{} % 一旦設定をクリア
% \cfoot{\thepage}
% \renewcommand{\headrulewidth}{0.0pt}
% \renewcommand{\footrulewidth}{0.0pt}
% }
% %% plain ページスタイルの再定義
% \fancypagestyle{plain}{
% \fancyhf{} % 一旦設定をクリア
% \fancyfoot[LE,RO]{\thepage}
% \renewcommand{\headrulewidth}{0pt}
% \renewcommand{\footrulewidth}{0.0pt}
% }

%% for listings
%\renewcommand{\lstlistingname}{List}
%\lstset{%
%  breaklines=true,%
%  breakautoindent=false,%
%  breakindent=0pt,%
%  fontadjust=true,%
%  backgroundcolor=\color{shadecolor},%
%  frame=single,%
%  framerule=0pt,%
%  basicstyle=\ttfamily\scriptsize,%
%  commentstyle=\color{reviewgreen},%
%  identifierstyle=\color{reviewblue},%
%  stringstyle=\color{reviewred},%
%  keywordstyle=\bfseries\color{reviewdarkred},%
%}
```

生成されたbook.texを見ると、zwの単位がそのままの形になっていたり、
冒頭にはLuaTeX-jaで読み込めないものが入っていたりします。

ファイルのはじめの方はこのような感じです。

``` tex
\documentclass[b5j,openany,oneside,papersize=b5j,notitlepage]{ltjsbook}
\usepackage[deluxe]{otf}
\usepackage[dvipdfmx]{color}
\usepackage[dvipdfmx]{graphicx}
\usepackage{framed}
\usepackage{wrapfig}
\definecolor{shadecolor}{gray}{0.9}
\definecolor{shadecolorb}{gray}{0.1}
\definecolor{reviewgreen}{rgb}{0,0.4,0}
\definecolor{reviewblue}{rgb}{0.2,0.2,0.4}
\definecolor{reviewred}{rgb}{0.7,0,0}
\definecolor{reviewdarkred}{rgb}{0.3,0,0}
\usepackage[utf8]{inputenc}
\usepackage{ascmac}
\usepackage{float}
\usepackage{alltt}
\usepackage{amsmath}

%% if you use @<u>{} (underline), use jumoline.sty
%%\usepackage{jumoline}

\newenvironment{shadedb}{%
  \def\FrameCommand{\fboxsep=\FrameSep \colorbox{shadecolorb}}%
  \MakeFramed {\FrameRestore}}%
 {\endMakeFramed}

\usepackage[top=10zw,bottom=12zw,left=10zw,right=10zw]{geometry}
%\usepackage[top=5zw,bottom=5zw,left=1zw,right=1zw]{geometry}


\newcommand{\parasep}{\vspace*{3zh}}
\setlength{\footskip}{30pt}

%% Bookmarkの文字化け対策（日本語向け）
\ifnum 46273=\euc"B4C1 % 46273 == 0xB4C1 == 漢(EUC-JP)
  \usepackage{atbegshi}%
  \AtBeginShipoutFirst{\special{pdf:tounicode EUC-UCS2}}%
  %%\AtBeginDvi{\special{pdf:tounicode EUC-UCS2}}%
\else
  \usepackage{atbegshi}%
  \AtBeginShipoutFirst{\special{pdf:tounicode 90ms-RKSJ-UCS2}}%
  %%\AtBeginDvi{\special{pdf:tounicode 90ms-RKSJ-UCS2}}%
\fi

\usepackage[dvipdfm,bookmarks=true,bookmarksnumbered=true,colorlinks=true,%
            pdftitle={書名},%
            pdfauthor={著者名}]{hyperref}
```

何か方法がありましたらご教授ください。
