### ISSUE TITLE
複数の設定YAMLファイルを読み込めるようにする

### ISSUE THREAD

**Issue by kmuto** [kmuto/review#503]
たとえば書名やISBNなどのcommonな情報を収録したYAMLファイルを用意し、各出力メディア向けのYAMLファイルではそれをincludeして利用できる、という手法をとれるようにしたい。

``!include``記法は実装によっては困るので、YAMLパラメータを新設する？（実装自体はたぶん簡単）

@kdmsnr さんのおっしゃっていたのはどんな手法？

**Comment by kdmsnr** [comment]
```yml
default: &default
  default_key: true

html:
  <<: *default
  html_specific_key: true

epub:
  <<: *default
  epub_specific_key: true
```

こうやって書いて、

```ruby
require 'yaml'
config = YAML.load(File.open("config.yml").read)
config["html"] #=> {"default_key"=>true, "html_specific_key"=>true}
config["epub"] #=> {"default_key"=>true, "epub_specific_key"=>true}
```

こうなる感じです。

**Comment by takahashim** [comment]
* `!include`の実装例: Includable YAML (http://r7kamura.github.io/2014/02/13/includable-yaml.html)
* Ansibleのplaybookでは`- include: foo.yml`みたいに書けるそうです http://docs.ansible.com/ansible/playbooks_roles.html

**Comment by kmuto** [comment]
@kdmsnr さんのだとそのhtmlとかepubとかを今度はどう指定するのか、ということになりそう。
!includeはYAML読み込み実装によってはにっちもさっちもになりそうなので、include:が実装としては無難でしょうか。

**Comment by kmuto** [comment]
YAMLファイルを複数指定して、重複は後が勝ち（要はどんどんmergeしていく）という案が@vvakameさんから出ています。

実装的には一番簡単ですが、指定の漏れや順序間違いをちょっと懸念しています。（これを使うケースがそもそも少なければ別によい、という考え方もありますが。）

**Comment by kdmsnr** [comment]
> そのhtmlとかepubとかを今度はどう指定するのか、ということになりそう。

ファイルを分割すれば、そのconfigファイルを指定するときで大丈夫だと思います。

config-html.yml:

```yaml
html:
  <<: *default
  html_specific_key: true
```
