### ISSUE TITLE
maprangeでシンタックスハイライトされない

### ISSUE THREAD

**Issue by KitaitiMakoto** [kmuto/review#657]
今日は。

痒い所に手が届くツールで、便利に使わせてもらっています。ありがとうございます。

epubmakerとwebmakerで、pygmentsによるシンタックスハイライトをしている時、`#@@maprange()`で抜粋した箇所がシンタックスハイライトされないのですが、単に抜粋するだけではいけないのでしょうか……？　同じ箇所が、PDFはpLaTeXのlistingsによってハイライトできています。また、`#@mapfile()`を使った場合はハイライトされます。

環境は以下の通りです。

* Ubuntu 16.04
* Ruby 2.3.1p112
* Re:VIEW 2.0.0
* pygments.rb 0.6.3
* Pygments 2.1.3

`config.yml`は次のようになっています。

```yaml
review_version: 2.0
bookname: bookname
booktitle: タイトル
language: ja
epubversion: 3
highlight:
  html: pygments
  latex: listings
stylesheet: main.css
stylesheet: main.css
texstyle: samplemacro
urnid: （ID）
```

コードを埋め込む部分は以下のようになっています（PHPです）。

```review
//list[path/to/source.php][source.php][php]{
#@maprange(path/to/source.php,head)
#@end
    // ...
#@maprange(path/to/source.php,__construct)
#@end
    // ...
#@maprange(path/to/source.php,newmethods)
#@end
//}
```
プリプロセスされたあとのコードがPHPとして正しいことは確認済みです。

うまくハイライトされる方法があったら教えてもらえますでしょうか。
他に必要な情報があれば言ってください。
よろしくお願いします。
